<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
		<string>i</string>
		<string>asm</string>
	</array>
	<key>name</key>
	<string>m6809-Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>"(\\"|[^"])*"</string>
			<key>name</key>
			<string>string.quoted.double.m6809</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'(\\'|[^'])*'</string>
			<key>name</key>
			<string>string.quoted.single.m6809</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;[^
]*
</string>
			<key>name</key>
			<string>comment.line.semicolon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|[ 	])\*(?![+-])[^
]*
</string>
			<key>name</key>
			<string>comment.line.asterisk</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.symbol.m6809</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^([a-zA-Z0-9_][a-zA-Z0-9_\.]*)(?=([ 	]*=|[ 	]+equ[ 	]+))</string>
			<key>name</key>
			<string>meta.equate.m6809</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.macro.m6809</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.other.macro.m6809</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(^([a-zA-Z0-9_\.]+)(:[ 	]*|[ 	]+)macro|^[ 	]+macro[ 	]+([a-zA-Z0-9_\.]+))[ 	]*$</string>
			<key>name</key>
			<string>meta.macro.m6809</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.section.name.m6809</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\bsection[ 	]+("[^"]+"|'[^']+'|[^,]+)</string>
			<key>name</key>
			<string>meta.section.m6809</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[a-zA-Z_]([a-zA-Z0-9_]*|[a-zA-Z0-9_\.%\$]*[a-zA-Z0-9_])(?=$|[ 	:])</string>
			<key>name</key>
			<string>variable.label.global.m6809</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z])\$[0-9A-Fa-f]+\b</string>
			<key>name</key>
			<string>constant.numeric.hex.m6809</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z])@[0-7]+\b</string>
			<key>name</key>
			<string>constant.numeric.octal.m6809</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z])%[01]+\b</string>
			<key>name</key>
			<string>constant.numeric.binary.m6809</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z])[+-]?[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.decimal.m6809</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(A|B|U|S|X|Y|PC|DP|CC)\b</string>
			<key>name</key>
			<string>variable.language.register.m6809</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)^[ \t]+\b(ADC[AB]|ADD[ABD]|AND[AB]|ASL[AB]?|ASR[AB]?|BIT[AB]|CLR[AB]?|CMP[ABDSUXY]|COM[AB]?|DAA|DEC[AB]?|EOR[AB]|EXG|INC[AB]?|LD[ABD]|LSL[AB]?|LSR[AB]?|MUL|NEG[AB]?|OR[AB]|ROL[AB]?|ROR[AB]?|SBC[AB]|ST[ABDSUXY]|SUB[ABD]|TST[AB]?|TFR|ADDD|SEX|LEA[SUXY]|LD[SUXY]|PSH[SU]|PUL[SU]|ABX|ANDCC|CWAI|NOP|ORCC|JMP|JSR|RTI|RTS|SWI[23]?|SYNC|L?B(CC|CS|EQ|GE|GT|HI|HS|LE|LO|LS|LT|MI|NE|PL|RA|RN|SR|VC|VS))\b</string>
			<key>name</key>
			<string>keyword.control.meta.cpu.m6809</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)^[ \t]+\b(IF|ELSEIF|ELSE|ENDIF|ENDM|FCB|FCC|FCN|FDB|DB|DW|FILL|RZB|ZMB|BSZ|ORG|PUT|RMB|SECTION|CODE|DATA|BSS|RAM|AUTO|SETDP|EQU|EXPORT|SET|END|INCLUDE|INCLUDEBIN)\b</string>
			<key>name</key>
			<string>keyword.control.meta.cpu.m6809</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm.m6809</string>
	<key>uuid</key>
	<string>fe8dd09c-dc33-41eb-83d4-4cc6ed720ad2</string>
</dict>
</plist>
